<?php
/**
 * Developer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DeveloperApiSdk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Restful API based on CoreAPI technology
 *
 * Add your description here
 *
 * OpenAPI spec version: 1.0.1
 * Contact: XXXXXXXXX@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\DeveloperApiSdk\Client\Model;

use \ArrayAccess;

/**
 * Developer Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Softonic\DeveloperApiSdk
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Developer implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Developer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id_developer' => 'string',
        'name' => 'string',
        'email' => 'string',
        'url' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id_developer' => 'id_developer',
        'name' => 'name',
        'email' => 'email',
        'url' => 'url'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id_developer' => 'setIdDeveloper',
        'name' => 'setName',
        'email' => 'setEmail',
        'url' => 'setUrl'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id_developer' => 'getIdDeveloper',
        'name' => 'getName',
        'email' => 'getEmail',
        'url' => 'getUrl'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_developer'] = isset($data['id_developer']) ? $data['id_developer'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['id_developer'] === null) {
            $invalid_properties[] = "'id_developer' can't be null";
        }
        if ((strlen($this->container['id_developer']) > 100)) {
            $invalid_properties[] = "invalid value for 'id_developer', the character length must be smaller than or equal to 100.";
        }

        if ((strlen($this->container['id_developer']) < 1)) {
            $invalid_properties[] = "invalid value for 'id_developer', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ((strlen($this->container['name']) > 100)) {
            $invalid_properties[] = "invalid value for 'name', the character length must be smaller than or equal to 100.";
        }

        if ((strlen($this->container['name']) < 1)) {
            $invalid_properties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['email']) && (strlen($this->container['email']) > 200)) {
            $invalid_properties[] = "invalid value for 'email', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['email']) && (strlen($this->container['email']) < 1)) {
            $invalid_properties[] = "invalid value for 'email', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['url']) && (strlen($this->container['url']) > 200)) {
            $invalid_properties[] = "invalid value for 'url', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['url']) && (strlen($this->container['url']) < 1)) {
            $invalid_properties[] = "invalid value for 'url', the character length must be bigger than or equal to 1.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['id_developer'] === null) {
            return false;
        }
        if (strlen($this->container['id_developer']) > 100) {
            return false;
        }
        if (strlen($this->container['id_developer']) < 1) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if (strlen($this->container['name']) > 100) {
            return false;
        }
        if (strlen($this->container['name']) < 1) {
            return false;
        }
        if (strlen($this->container['email']) > 200) {
            return false;
        }
        if (strlen($this->container['email']) < 1) {
            return false;
        }
        if (strlen($this->container['url']) > 200) {
            return false;
        }
        if (strlen($this->container['url']) < 1) {
            return false;
        }
        return true;
    }


    /**
     * Gets id_developer
     * @return string
     */
    public function getIdDeveloper()
    {
        return $this->container['id_developer'];
    }

    /**
     * Sets id_developer
     * @param string $id_developer Developer identifier
     * @return $this
     */
    public function setIdDeveloper($id_developer)
    {
        if (strlen($id_developer) > 100) {
            throw new \InvalidArgumentException('invalid length for $id_developer when calling Developer., must be smaller than or equal to 100.');
        }
        if (strlen($id_developer) < 1) {
            throw new \InvalidArgumentException('invalid length for $id_developer when calling Developer., must be bigger than or equal to 1.');
        }
        $this->container['id_developer'] = $id_developer;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Developer name
     * @return $this
     */
    public function setName($name)
    {
        if (strlen($name) > 100) {
            throw new \InvalidArgumentException('invalid length for $name when calling Developer., must be smaller than or equal to 100.');
        }
        if (strlen($name) < 1) {
            throw new \InvalidArgumentException('invalid length for $name when calling Developer., must be bigger than or equal to 1.');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     * @param string $email Developer email
     * @return $this
     */
    public function setEmail($email)
    {
        if (strlen($email) > 200) {
            throw new \InvalidArgumentException('invalid length for $email when calling Developer., must be smaller than or equal to 200.');
        }
        if (strlen($email) < 1) {
            throw new \InvalidArgumentException('invalid length for $email when calling Developer., must be bigger than or equal to 1.');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets url
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     * @param string $url Developer url
     * @return $this
     */
    public function setUrl($url)
    {
        if (strlen($url) > 200) {
            throw new \InvalidArgumentException('invalid length for $url when calling Developer., must be smaller than or equal to 200.');
        }
        if (strlen($url) < 1) {
            throw new \InvalidArgumentException('invalid length for $url when calling Developer., must be bigger than or equal to 1.');
        }
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Softonic\DeveloperApiSdk\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Softonic\DeveloperApiSdk\ObjectSerializer::sanitizeForSerialization($this));
    }
}


