<?php
/**
 * DevelopersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DeveloperApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Restful API based on CoreAPI technology
 *
 * Add your description here
 *
 * OpenAPI spec version: v2.112.0
 * Contact: XXXXXXXXX@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\DeveloperApiSdk;

use \Softonic\DeveloperApiSdk\Configuration;
use \Softonic\DeveloperApiSdk\ApiException;
use \Softonic\DeveloperApiSdk\ObjectSerializer;

/**
 * DevelopersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\DeveloperApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DevelopersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDeveloper
     *
     * Creates a new Developer.
     *
     */
    public function testCreateDeveloper()
    {
    }

    /**
     * Test case for findDeveloper
     *
     * List of Developers.
     *
     */
    public function testFindDeveloper()
    {
    }

    /**
     * Test case for readDeveloper
     *
     * Fetches a single Developer.
     *
     */
    public function testReadDeveloper()
    {
    }

    /**
     * Test case for replaceDeveloper
     *
     * Entirely replaces a Developer.
     *
     */
    public function testReplaceDeveloper()
    {
    }

    /**
     * Test case for updateDeveloper
     *
     * Partially updates a Developer.
     *
     */
    public function testUpdateDeveloper()
    {
    }
}
